server:
  port: 0
  servlet:
    session:
      timeout: 120s

spring:
  application:
    name: studio-chat-01
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: core,web
  mvc:
    async:
      request-timeout: 120s
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
